emtato/csc207-project

src/main/java/view/Alert.java, src/main/java/view/ChangePassword.java, src/main/java/view/GUIConstants.java, src/main/java/view/HomeView.java, src/main/java/view/Modify.java
In src/main/java/view/, I:
- Cleaned up the code in Alert.java
- Modified Modify.java and ChangePassword.java (hopefully they work, but I still need to figure out how to implement use cases)
- Removed some magic numbers in the code
Still need to figure out how to combine HomeView.java and HomePageView.java
=> mainly alert, changepassword, modify (check if works)

src/main/java/app/AppBuilder.java, src/main/java/data_access/InMemoryUserDataAccessObject.java, src/main/java/entity/Account.java, src/main/java/interface_adapter/login/LoginPresenter.java, src/main/java/use_case/signup/SignupInteractor.java, src/main/java/view/AnalyzeRecipesView.java, src/main/java/view/ExploreEventsView.java, src/main/java/view/ExploreView.java, src/main/java/view/LoginView.java, src/main/java/view/MenuBarPanel.java, src/main/java/view/SignupView.java
Linked sign up and login views to other views via buttons, also inserted the centralized interactive menu bar with the other views
=> linked sign up and login views to rest of views

src/main/java/app/AppBuilder.java, src/main/java/data_access/spoonacular/SpoonacularAPI.java, src/main/java/entity/Post.java, src/main/java/entity/Recipe.java, src/main/java/view/PostView.java
important– restructuring Recipe object to extend Post, decluttering redundant fields and streamlining object creation
=> Recipe extends Post

src/main/java/app/AppBuilder.java, src/main/java/app/Main.java, src/main/java/data_access/data_storage.json, src/main/java/view/ClubHomePageView.java, src/main/java/view/SpecificClubView.java
club specific view mainly complete
=> club specific view mainly complete

src/main/java/app/AppBuilder.java, src/main/java/app/Main.java, src/main/java/data_access/DataStorage.java, src/main/java/data_access/data_storage.json, src/main/java/entity/Club.java, src/main/java/entity/Review.java, src/main/java/view/ClubHomePageView.java, src/main/java/view/CreateClubView.java
created club view, started working on database for clubs
=> created club view, started working on database for clubs

src/main/java/data_access/FileUserDataAccessObject.java, src/main/java/data_access/InMemoryUserDataAccessObject.java, src/main/java/interface_adapter/manage_following/ManageFollowingController.java, src/main/java/interface_adapter/manage_following/ManageFollowingPresenter.java, src/main/java/interface_adapter/manage_following/ManageFollowingState.java, src/main/java/interface_adapter/manage_following/ManageFollowingViewModel.java, src/main/java/interface_adapter/profile/ProfilePresenter.java, src/main/java/use_case/manage_following/ManageFollowingInputBoundary.java, src/main/java/use_case/manage_following/ManageFollowingInputData.java, src/main/java/use_case/manage_following/ManageFollowingInteractor.java, src/main/java/use_case/manage_following/ManageFollowingUserDataAccessInterface.java, src/main/java/view/ManageFollowingView.java
and fixed a few things for the following related usecases
=> implemented the follow account use case in manage following section

src/main/java/app/AppBuilder.java, src/main/java/app/Session.java, src/main/java/data_access/DBPostCommentLikesDataAccessObject.java, src/main/java/data_access/data_storage.json, src/main/java/data_access/user_data.json, src/main/java/interface_adapter/ViewManagerModel.java, src/main/java/view/CreateNewPostView.java, src/main/java/view/HomePageView.java
createnewpostview refreshes and clears info when revisited
=> creating new post updates immediately on homepageview

src/main/java/data_access/data_storage.json, src/main/java/interface_adapter/post_view/PostController.java, src/main/java/use_case/like_post/LikePostDataAccessInterface.java, src/main/java/use_case/like_post/LikePostInputBoundary.java, src/main/java/use_case/like_post/LikePostInputData.java, src/main/java/use_case/like_post/LikePostInteractor.java, src/main/java/use_case/like_post/LikePostOutputBoundary.java, src/main/java/view/PostView.java
postview integrates images in scrolling
postview ui improvements
starting to add 🤮use cases organization
wrap text on main pane fully done
=> postview improvements and use cases organization

src/main/java/data_access/FileUserDataAccessObject.java, src/main/java/data_access/data_storage.json, src/main/java/data_access/user_data.json
changed some things in the FileUserDataAccessObject file and then had to remove the data stored in the user json file
=> fixed the FileUserDataAccessObject for my use cases

src/main/java/app/AppBuilder.java, src/main/java/app/Main.java, src/main/java/data_access/data_storage.json
=> made appbuiler a singleton

src/main/java/view/SettingsView.java, src/test/java/use_case/change_password/ChangePasswordInteractorTest.java, src/test/java/use_case/delete_account/DeleteAccountInteractorTest.java
added two files in the tests folder
=> added interactor tests for change password and delete account

src/main/java/view/ClubHomePageView.java
fixed minor bug with announcements panel in ClubHomePageView.java
=> fixed minor bug with announcements panel in ClubHomePageView.java

src/main/java/app/AppBuilder.java, src/main/java/app/Main.java, src/main/java/app/Session.java, src/main/java/data_access/data_storage.json, src/main/java/view/ClubHomePageView.java, src/main/java/view/HomePageView.java, src/main/java/view/PostView.java, src/main/java/view/ProfileView.java, src/main/java/view/SpecificClubView.java, src/main/java/view/ui_components/PostPanel.java
made changes related to PostPanel and related views to move use case creation to the AppBuilder file and out of the view files, which removes the dependency of views on daos
=> refactored files for clean architecture/solid

src/main/java/data_access/DBPostCommentLikesDataAccessObject.java, src/main/java/entity/Post.java, src/main/java/entity/Review.java, src/main/java/view/ReviewStarSystem.java
Reverts emtato/csc207-project#150
=> Revert "trying to add review to database"

src/main/java/app/AppBuilder.java, src/main/java/app/AppDirector.java, src/main/java/app/Munchables.java, src/main/java/app/TempClass.java, src/main/java/app/UseCaseBuilder.java, src/main/java/app/ViewBuilder.java, src/main/java/data_access/user_data.json, src/main/java/view/HomePageView.java
made an App Director that uses a ViewBuilder and UseCaseBuilder to build the application since AppBuilder was getting too complicated and copied code from app builder into viewbuilder and usecase builder respectively
=> made a better app builder

src/main/java/data_access/DBUserDataAccessObject.java, src/main/java/data_access/FileUserDataAccessObject.java, src/main/java/data_access/InMemoryUserDataAccessObject.java, src/main/java/data_access/data_storage.json, src/main/java/data_access/user_data.json, src/main/java/entity/Account.java, src/main/java/entity/User.java, src/main/java/interface_adapter/manage_followers/ManageFollowersController.java, src/main/java/interface_adapter/manage_followers/ManageFollowersPresenter.java, src/main/java/interface_adapter/manage_followers/ManageFollowersState.java, src/main/java/interface_adapter/manage_followers/ManageFollowersViewModel.java, src/main/java/interface_adapter/manage_following/ManageFollowingPresenter.java, src/main/java/interface_adapter/manage_following/ManageFollowingState.java, src/main/java/interface_adapter/manage_following/ManageFollowingViewModel.java, src/main/java/interface_adapter/view_profile/ProfilePresenter.java, src/main/java/use_case/manage_followers/ManageFollowersInputBoundary.java, src/main/java/use_case/manage_followers/ManageFollowersInputData.java, src/main/java/use_case/manage_followers/ManageFollowersInteractor.java, src/main/java/use_case/manage_followers/ManageFollowersOutputData.java, src/main/java/use_case/manage_followers/ManageFollowersUserDataAccessInterface.java, src/main/java/use_case/manage_following/ManageFollowingInteractor.java, src/main/java/use_case/manage_following/ManageFollowingOutputData.java, src/main/java/use_case/manage_following/ManageFollowingUserDataAccessInterface.java, src/main/java/use_case/view_profile/ProfileInteractor.java, src/main/java/use_case/view_profile/SwitchToFollowersViewOutputData.java, src/main/java/use_case/view_profile/SwitchToFollowingViewOutputData.java, src/main/java/view/ManageFollowersView.java, src/main/java/view/ManageFollowingView.java, src/main/java/view/ui_components/UserInfoPanel.java
…, and to accept follow requests. also made the manage following and manage followers pages look better
=> implemented the option to request to follow an account if its private

src/main/java/app/AppBuilder.java, src/main/java/app/AppDirector.java, src/main/java/app/ViewBuilder.java, src/main/java/data_access/DBClubsDataAccessObject.java, src/main/java/data_access/DBPostCommentLikesDataAccessObject.java, src/main/java/data_access/FilePostCommentLikesDataAccessObject.java, src/main/java/data_access/InMemoryPostCommentLikesDataAccessObject.java, src/main/java/data_access/PostCommentsLikesDataAccessObject.java, src/main/java/data_access/data_storage.json, src/main/java/entity/Post.java, src/main/java/entity/Recipe.java, src/main/java/interface_adapter/create_post_view/CreatePostController.java, src/main/java/interface_adapter/create_post_view/CreatePostPresenter.java, src/main/java/interface_adapter/create_post_view/CreatePostState.java, src/main/java/use_case/create_post/CreatePostInputData.java, src/main/java/use_case/create_post/CreatePostInteractor.java, src/main/java/use_case/create_post/CreatePostOutputBoundary.java, src/main/java/view/ClubHomePageView.java, src/main/java/view/CreateNewPostView.java, src/main/java/view/SpecificClubView.java
saved announcement and general club posts to database for each individual club
=> announcement and general club posts

src/main/java/interface_adapter/view_profile/ProfilePresenter.java, src/main/java/use_case/view_profile/ProfileInteractor.java, src/main/java/view/ProfileView.java
made it so you can only view a different profile if it is public or you are following that account.
=> fixed the view other profile feature

src/main/java/data_access/InMemoryClubsDataAccessObject.java, src/test/java/use_case/clubs_home/ClubInteractorTest.java, src/test/java/use_case/create_club/CreateClubInteractorTest.java, src/test/java/use_case/specific_club/SpecificClubInteractorTest.java
/home/kate/IdeaProjects/csc207-project/src/test/java/use_case/clubs_home/ClubInteractorTest.java:80:41
java: constructor CreateClubInputData in class use_case.create_club.CreateClubInputData cannot be applied to given types;
required: java.lang.String,java.lang.String,java.lang.String,java.util.List<java.lang.String>,java.util.List<java.lang.String>
found:    java.lang.String,java.lang.String,java.util.ArrayList<java.lang.String>,java.util.ArrayList<java.lang.String>
reason: actual and formal argument lists differ in length
=> made tests for club related use cases

src/main/java/app/AppDirector.java
added a method for using in memory daos to build the app and documentation
=> added new method in app director

src/main/java/data_access/DBPostCommentLikesDataAccessObject.java, src/main/java/data_access/DBUserDataAccessObject.java, src/main/java/data_access/FileClubsDataAccessObject.java, src/main/java/data_access/FilePostCommentLikesDataAccessObject.java, src/main/java/data_access/FileUserDataAccessObject.java, src/main/java/data_access/data_storage.json, src/main/java/entity/Account.java, src/main/java/entity/Post.java, src/main/java/use_case/clubs_home/ClubInteractor.java, src/main/java/view/ClubHomePageView.java
fixed issue with storing/managing user club data and club post data
=> fixed issue with storing/managing user club data and club post data

src/main/java/data_access/DBUserDataAccessObject.java, src/main/java/data_access/FilePostCommentLikesDataAccessObject.java, src/main/java/data_access/FileUserDataAccessObject.java, src/main/java/data_access/data_storage.json, src/main/java/data_access/user_data.json, src/main/java/use_case/create_post/CreatePostInteractor.java, src/main/java/view/CreateNewPostView.java
fixed another issue about club post data
=> fixed another issue about club post data

src/main/java/app/ViewBuilder.java, src/main/java/data_access/ClubsDataAccessObject.java, src/main/java/data_access/DBClubsDataAccessObject.java, src/main/java/data_access/DBPostCommentLikesDataAccessObject.java, src/main/java/data_access/DBUserDataAccessObject.java, src/main/java/data_access/FileClubsDataAccessObject.java, src/main/java/data_access/FilePostCommentLikesDataAccessObject.java, src/main/java/data_access/InMemoryClubsDataAccessObject.java, src/main/java/data_access/InMemoryPostCommentLikesDataAccessObject.java, src/main/java/data_access/UserDataAccessObject.java, src/main/java/entity/Club.java, src/main/java/interface_adapter/create_club/CreateClubController.java, src/main/java/use_case/create_club/CreateClubClubsDataAccessInterface.java, src/main/java/use_case/create_club/CreateClubInteractor.java, src/main/java/use_case/delete_club/DeleteClubInteractor.java, src/main/java/use_case/join_club/JoinClubInteractor.java, src/main/java/use_case/leave_club/LeaveClubInteractor.java, src/main/java/use_case/list_clubs/ListClubsInteractor.java, src/main/java/view/ClubHomePageView.java, src/main/java/view/CreateClubView.java, src/main/java/view/CreateNewPostView.java, src/main/java/view/SpecificClubView.java, src/main/java/view/ui_components/RoundImagePanel.java, src/test/java/use_case/create_club/CreateClubInteractorTest.java, src/test/java/use_case/delete_club/DeleteClubInteractorTest.java, src/test/java/use_case/join_club/JoinClubInteractorTest.java, src/test/java/use_case/leave_club/LeaveClubInteractorTest.java, src/test/java/use_case/list_clubs/ListClubsInteractorTest.java, src/test/java/view/CreateNewPostViewTest.java
fixed delete club bug (somehow deleted random users from the database oops???)
=> fixed delete club bug (somehow deleted random users from the database oops???)

src/main/java/app/UseCaseBuilder.java, src/main/java/interface_adapter/create_club/CreateClubController.java, src/main/java/interface_adapter/create_club/CreateClubPresenter.java, src/main/java/interface_adapter/select_club_members/SelectClubMembersController.java, src/main/java/interface_adapter/select_club_members/SelectClubMembersPresenter.java, src/main/java/use_case/create_club/CreateClubInputBoundary.java, src/main/java/use_case/create_club/CreateClubInteractor.java, src/main/java/use_case/create_club/CreateClubOutputBoundary.java, src/main/java/use_case/select_club_members/SelectClubMembersInputBoundary.java, src/main/java/use_case/select_club_members/SelectClubMembersInteractor.java, src/main/java/use_case/select_club_members/SelectClubMembersOutputBoundary.java, src/main/java/view/CreateClubView.java, src/test/java/use_case/create_club/CreateClubInteractorTest.java, src/test/java/use_case/select_club_members/SelectClubMembersInteractorTest.java, src/test/java/use_case/specific_club/SpecificClubInteractorTest.java
created SelectClubMembers use case so that CreateClubInteractor follows SRP
=> created SelectClubMembers use case so that CreateClubInteractor follows SRP
